# Generated by Django 3.2.9 on 2022-02-12 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('managers', models.ManyToManyField(blank=True, default=None, related_name='managers', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, default=None, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
