# Generated by Django 3.2.9 on 2022-03-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='managers',
        ),
    ]
