version: "3.9"
services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: worktimemanager
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/db:/var/lib/posgresql/data
  zuri:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/worktimemanager
    command: bash -c "python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db:db