# Generated by Django 3.2.9 on 2022-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
