# Generated by Django 3.2.9 on 2022-02-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220203_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtmuser',
            name='promotedToManager',
            field=models.BooleanField(default=False),
        ),
    ]
