# Generated by Django 3.2.9 on 2022-02-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('accounts', '0006_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtmuser',
            name='group',
            field=models.ManyToManyField(blank=True, default=None, related_name='group', to='teams.Team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
