# Generated by Django 3.2.9 on 2022-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220212_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtmuser',
            old_name='group',
            new_name='team',
        ),
    ]
