# Generated by Django 3.2.9 on 2022-02-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_group_wtmuser_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtmuser',
            name='team',
        ),
    ]
