# Generated by Django 3.2.9 on 2022-02-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('accounts', '0009_remove_wtmuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtmuser',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='teams.team'),
        ),
    ]
