# Generated by Django 3.2.9 on 2022-02-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_wtmuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtmuser',
            name='personalBreakTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtmuser',
            name='personalEndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtmuser',
            name='personalStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
