# Generated by Django 3.2.9 on 2022-02-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220223_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtmuser',
            name='personalBreakTime',
        ),
        migrations.RemoveField(
            model_name='wtmuser',
            name='personalEndTime',
        ),
        migrations.RemoveField(
            model_name='wtmuser',
            name='personalStartTime',
        ),
    ]
