# Generated by Django 3.2.9 on 2022-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220223_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtmuser',
            name='personalBreakTime',
            field=models.TimeField(default='00:25', null=True),
        ),
        migrations.AddField(
            model_name='wtmuser',
            name='personalEndTime',
            field=models.TimeField(default='16:25', null=True),
        ),
        migrations.AddField(
            model_name='wtmuser',
            name='personalStartTime',
            field=models.TimeField(default='08:00', null=True),
        ),
    ]
