# Generated by Django 3.2.9 on 2022-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absenceType',
            field=models.CharField(choices=[('VACATIONP', 'Vacation leave paid'), ('VACATIONNP', 'Vacation leave not paid'), ('ONDEMAND', 'On demand')], default='VACATIONP', max_length=17),
        ),
    ]
