# Generated by Django 3.2.9 on 2022-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_alter_absence_absencetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
