# Generated by Django 3.2.9 on 2022-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_auto_20220303_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absenceType',
            field=models.CharField(choices=[('VACATIONP', 'Vacation leave paid'), ('VACATIONNP', 'Vacation leave not paid'), ('ONDEMAND', 'On demand'), ('SICKLEAVE', 'Sick leave')], default='VACATIONP', max_length=17),
        ),
    ]
