# Generated by Django 3.2.9 on 2022-03-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_alter_absence_absencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='statusType',
            field=models.CharField(choices=[('SENTTOAPPROVE', 'Sent to approve'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved')], default='SENTTOAPPROVE', max_length=17),
        ),
    ]
