# Generated by Django 3.2.9 on 2022-02-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('breakTime', models.TimeField()),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(blank=True, default=None, related_name='days', to=settings.AUTH_USER_MODEL)),
                ('managerToAccept', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='managerToAccept', to=settings.AUTH_USER_MODEL)),
                ('timesheetOwner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timesheetOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
