# Generated by Django 3.2.9 on 2022-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetday',
            name='date',
            field=models.DateField(),
        ),
    ]
