# Generated by Django 3.2.9 on 2022-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_timesheet_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='month',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
