# Generated by Django 3.2.9 on 2022-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20220216_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetday',
            name='breakTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='timesheetday',
            name='endTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='timesheetday',
            name='startTime',
            field=models.TimeField(default=None),
        ),
    ]
