# Generated by Django 3.2.9 on 2022-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_auto_20220217_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetday',
            name='workTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='timesheetday',
            name='breakTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='timesheetday',
            name='endTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='timesheetday',
            name='startTime',
            field=models.TimeField(default='00:00'),
        ),
    ]
