# Generated by Django 3.2.9 on 2022-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_auto_20220217_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='sentToAccept',
            field=models.BooleanField(default=False),
        ),
    ]
