# Generated by Django 3.2.9 on 2022-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_auto_20220217_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='totalWorkHours',
            field=models.TimeField(default='00:00'),
        ),
    ]
