# Generated by Django 3.2.9 on 2022-02-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_timesheet_totalworkhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='totalWorkHours',
        ),
    ]
