# Generated by Django 3.2.9 on 2022-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_remove_timesheet_totalworkhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='totalWorkHours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
