# Generated by Django 3.2.9 on 2022-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_timesheet_sentbackforchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='monthNumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
