# Generated by Django 3.2.9 on 2022-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0013_timesheet_monthnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheetStatus',
            field=models.CharField(choices=[('CR', 'Created'), ('STA', 'Sent to approve'), ('SBFC', 'Sent back for change'), ('AP', 'Approved')], default='CR', max_length=4),
        ),
    ]
