# Generated by Django 3.2.9 on 2022-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0014_timesheet_timesheetstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='timesheetStatus',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SENTTOAPPROVE', 'Sent to approve'), ('SENTBACKFORCHANGE', 'Sent back for change'), ('APPROVED', 'Approved')], default='CREATED', max_length=17),
        ),
    ]
